// kelime-oyun-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Observable, of } from 'rxjs';
import { catchError, map } from 'rxjs/operators';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'kelime-oyun-angular';


   sorular = [
    {
      soru: "Siyah ile aynı anlama gelen bir renk",
      cevap: "Kara",
      soruldu: false
    },
    {
      soru: "Sık kullanılan bir isim",
      cevap: "Ahmet",
      soruldu: false
    },
    {
      soru: "Türkiye'nin başkenti",
      cevap: "Ankara",
      soruldu: false
    },
    {
      soru: "Karadenizde bir ilimiz",
      cevap: "Giresun",
      soruldu: false
    }
  ];
  
  mesaj =  null;
  mesajClass = "";
  mesajSure = null;
  mevcutSoru = null;
  harfler = new Array();
  puan= 0;
  harfPuan= 0;
  yarismaciCevap = "";
  tamamlandi = false;
  sure = null;
  kalanSure= 0;
   ages = [3, 10, 18, 20];
   
   checkAdult(age:any) {
    return age >= 18;
  }

  basla() {

    this.tamamlandi =false;
    this.mevcutSoru =null;
    this.puan =0;
    
    this.kalanSure =60;
    this.sure = setInterval(() => {
        this.kalanSure--;
//        console.log(this.kalanSure);

        if (this.kalanSure === 0) {
          this.bitir();
        }
    } ,1000);
        

    this.soruVer();
  }

 bitir() {
      this.tamamlandi=true;
      this.mevcutSoru =null;
      clearInterval(this.sure);
    }

    soruVer() {
      this.yarismaciCevap ='';
      this.mevcutSoru = this.sorular.find(x => !x.soruldu);

      if (!this.mevcutSoru) {
        
        this.bitir();
        return;
      }

      this.harfler = new Array();
      
      this.mevcutSoru.cevap.split("").map(x => {
        
        this.harfler.push({
          harf: x,
          acildi: false
        });
      });
      this.harfPuan = this.harfler.length * 100;
      this.mevcutSoru.soruldu = true;
    }

    cevapVer() {
      let cevap = this.yarismaciCevap.toLocaleUpperCase();
      this.yarismaciCevap = cevap;
        
      if (
        this.mevcutSoru.cevap.toLocaleUpperCase() ===
        cevap.toLocaleUpperCase()
      ) {
        this.puan += this.harfPuan;
      } 
      else {
       this.puan -= this.harfPuan;
      }

      this.soruVer();
    }

    harfVer() {
      let rastgeleHarfIndex = Math.floor(this.harfler.length * Math.random());

      if (this.harfPuan <= 100) {
        return;
      }

      let harf = this.harfler[rastgeleHarfIndex];
      while (harf.acildi) {
        rastgeleHarfIndex = Math.floor(this.harfler.length * Math.random());
        harf = this.harfler[rastgeleHarfIndex];
      }
      harf.acildi = true;
      this.harfPuan -= 100;
    }
}

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    margin: 8px 0;
  }

  p {
    margin: 0;
  }

  .spacer {
    flex: 1;
  }

  .toolbar {
    height: 60px;
    margin: -8px;
    display: flex;
    align-items: center;
    background-color: #1976d2;
    color: white;
    font-weight: 600;
  }

  .toolbar img {
    margin: 0 16px;
  }

  .toolbar #twitter-logo {
    height: 40px;
    margin: 0 16px;
  }

  .toolbar #twitter-logo:hover {
    opacity: 0.8;
  }

  .content {
    display: flex;
    margin: 32px auto;
    padding: 0 16px;
    max-width: 960px;
    flex-direction: column;
    align-items: center;
  }

  svg.material-icons {
    height: 24px;
    width: auto;
  }

  svg.material-icons:not(:last-child) {
    margin-right: 8px;
  }

  .card svg.material-icons path {
    fill: #888;
  }

  .card-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    margin-top: 16px;
  }

 

  .card-container .card:not(:last-child) {
    margin-right: 0;
  }

  .card.card-small {
    height: 16px;
    width: 168px;
  }

  .card-container .card:not(.highlight-card) {
    cursor: pointer;
  }

  .card-container .card:not(.highlight-card):hover {
    transform: translateY(-3px);
    box-shadow: 0 4px 17px rgba(black, 0.35);
  }

  .card-container .card:not(.highlight-card):hover .material-icons path {
    fill: rgb(105, 103, 103);
  }

  .card.highlight-card {
    background-color: #1976d2;
    color: white;
    font-weight: 600;
    border: none;
    width: auto;
    min-width: 30%;
    position: relative;
  }

  .card.card.highlight-card span {
    margin-left: 60px;
  }

  svg#rocket {
    width: 80px;
    position: absolute;
    left: -10px;
    top: -24px;
  }

  svg#rocket-smoke {
    height: 100vh;
    position: absolute;
    top: 10px;
    right: 180px;
    z-index: -10;
  }

  a,
  a:visited,
  a:hover {
    color: #1976d2;
    text-decoration: none;
  }

  a:hover {
    color: #125699;
  }

  .terminal {
    position: relative;
    width: 80%;
    max-width: 600px;
    border-radius: 6px;
    padding-top: 45px;
    margin-top: 8px;
    overflow: hidden;
    background-color: rgb(15, 15, 16);
  }

  .terminal::before {
    content: "\2022 \2022 \2022";
    position: absolute;
    top: 0;
    left: 0;
    height: 4px;
    background: rgb(58, 58, 58);
    color: #c2c3c4;
    width: 100%;
    font-size: 2rem;
    line-height: 0;
    padding: 14px 0;
    text-indent: 4px;
  }

  .terminal pre {
    font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
    color: white;
    padding: 0 1rem 1rem;
    margin: 0;
  }

  .circle-link {
    height: 40px;
    width: 40px;
    border-radius: 40px;
    margin: 8px;
    background-color: white;
    border: 1px solid #eeeeee;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    transition: 1s ease-out;
  }

  .circle-link:hover {
    transform: translateY(-0.25rem);
    box-shadow: 0px 3px 15px rgba(0, 0, 0, 0.2);
  }

  footer {
    margin-top: 8px;
    display: flex;
    align-items: center;
    line-height: 20px;
  }

  footer a {
    display: flex;
    align-items: center;
  }



  svg#clouds {
    position: fixed;
    bottom: -160px;
    left: -230px;
    z-index: -10;
    width: 1920px;
  }


  /* Responsive Styles */
  @media screen and (max-width: 767px) {

    .card-container > *:not(.circle-link) ,
    .terminal {
      width: 100%;
    }

    .card:not(.highlight-card) {
      height: 16px;
      margin: 8px 0;
    }

    .card.highlight-card span {
      margin-left: 72px;
    }

    svg#rocket-smoke {
      right: 120px;
      transform: rotate(-5deg);
    }
  }

  @media screen and (max-width: 575px) {
    svg#rocket-smoke {
      display: none;
      visibility: hidden;
    }
  }

  .harf {
  width: 100px;
  height: 100px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 30pt;
}
</style>

<!-- Toolbar -->
<div class="toolbar" role="banner">
  <img
    width="40"
    alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
  />
  <span>Welcome</span>
    <div class="spacer"></div>
  <a aria-label="Angular on twitter" href="https://twitter.com/angular" title="Twitter">
    
    <svg id="twitter-logo" height="24" data-name="Logo — FIXED" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400">
      <defs>
        <style>
          .cls-1 {
            fill: none;
          }

          .cls-2 {
            fill: #ffffff;
          }
        </style>
      </defs>
      <rect class="cls-1" width="400" height="400" />
      <path class="cls-2" d="M153.62,301.59c94.34,0,145.94-78.16,145.94-145.94,0-2.22,0-4.43-.15-6.63A104.36,104.36,0,0,0,325,122.47a102.38,102.38,0,0,1-29.46,8.07,51.47,51.47,0,0,0,22.55-28.37,102.79,102.79,0,0,1-32.57,12.45,51.34,51.34,0,0,0-87.41,46.78A145.62,145.62,0,0,1,92.4,107.81a51.33,51.33,0,0,0,15.88,68.47A50.91,50.91,0,0,1,85,169.86c0,.21,0,.43,0,.65a51.31,51.31,0,0,0,41.15,50.28,51.21,51.21,0,0,1-23.16.88,51.35,51.35,0,0,0,47.92,35.62,102.92,102.92,0,0,1-63.7,22A104.41,104.41,0,0,1,75,278.55a145.21,145.21,0,0,0,78.62,23"
      />
    </svg>
    
  </a>
</div>

<div class="content" role="main">

 



  <div id="app" class="container mt-4">
    <div class="card mb-4" *ngIf="tamamlandi">
      <div class="card-body">
        Tebrikleri yarışmayı {{this.puan}} ile tamamladınız
      </div>
    </div>

    <div class="card mt-4" *ngIf="!mevcutSoru">
      <div class="card-header">
        <h5 class="mb-0">Kelime Oyunu Yarışmasına Hoşgeldiniz!</h5>
      </div>
      <div class="card-body">Yarışmaya Başlamak için yarışmaya başla buttonuna basın</div>
      <div class="card-footer">
        <button class="btn btn-primary" (click)="basla()">Yarışmaya Başla</button>
      </div> 
    </div>
    <div class="card" *ngIf="mevcutSoru">
      <div class="card-header"><h3 class="mb-0">{{mevcutSoru.soru}}</h3></div>
      <div class="card-body">
        <div class="d-flex">
          <div class="harf shadow mr-3" *ngFor="let harf of harfler">
            <span *ngIf="harf.acildi;else acilmadi">{{harf.harf}}</span>
            <ng-template #acilmadi><span ></span></ng-template>
        
          </div>
        </div>
      </div>
      <div class="card-footer">
        <div class="d-flex">
          <div class="mr-4">Harf puan {{harfPuan}}</div>
          <div class="mr-4">Toplam puan {{puan}}</div>
           <div class="mr-4">Kalan süreniz <kbd>{{kalanSure}}</kbd></div>
        </div>
      </div>

      <div class="card-footer">
        <div class="input-group mb-3">
           <input
            class="form-control"
            type="text"
            placeholder="Cevap giriniz"
            [(ngModel)]="yarismaciCevap"
          />
          <div class="input-group-append">
                  <button class="btn btn-success" (click)="cevapVer()">Cevap Ver</button>
          </div>
        </div>
 
      </div>
      <div class="card-footer">
        <button class="btn btn-secondary" (click)="harfVer()" >Harf ver</button>
      </div>
    </div>
  </div>




  <svg id="clouds" alt="Gray Clouds Background" xmlns="http://www.w3.org/2000/svg" width="2611.084" height="485.677" viewBox="0 0 2611.084 485.677">
    <path id="Path_39" data-name="Path 39" d="M2379.709,863.793c10-93-77-171-168-149-52-114-225-105-264,15-75,3-140,59-152,133-30,2.83-66.725,9.829-93.5,26.25-26.771-16.421-63.5-23.42-93.5-26.25-12-74-77-130-152-133-39-120-212-129-264-15-54.084-13.075-106.753,9.173-138.488,48.9-31.734-39.726-84.4-61.974-138.487-48.9-52-114-225-105-264,15a162.027,162.027,0,0,0-103.147,43.044c-30.633-45.365-87.1-72.091-145.206-58.044-52-114-225-105-264,15-75,3-140,59-152,133-53,5-127,23-130,83-2,42,35,72,70,86,49,20,106,18,157,5a165.625,165.625,0,0,0,120,0c47,94,178,113,251,33,61.112,8.015,113.854-5.72,150.492-29.764a165.62,165.62,0,0,0,110.861-3.236c47,94,178,113,251,33,31.385,4.116,60.563,2.495,86.487-3.311,25.924,5.806,55.1,7.427,86.488,3.311,73,80,204,61,251-33a165.625,165.625,0,0,0,120,0c51,13,108,15,157-5a147.188,147.188,0,0,0,33.5-18.694,147.217,147.217,0,0,0,33.5,18.694c49,20,106,18,157,5a165.625,165.625,0,0,0,120,0c47,94,178,113,251,33C2446.709,1093.793,2554.709,922.793,2379.709,863.793Z" transform="translate(142.69 -634.312)" fill="#eee"/>
  </svg>

</div>



<router-outlet></router-outlet>

// kelime-oyun-vue/src/App.vue
<template>
  <div id="app" class="container mt-4">
    <div class="card mb-4" v-if="tamamlandi">
      <div class="card-body">
        Tebrikleri yarışmayı {{this.puan}} ile tamamladınız
      </div>
    </div>

    <div class="card mt-4" v-if="!mevcutSoru">
      <div class="card-header">
        <h5 class="mb-0">Kelime Oyunu Yarışmasına Hoşgeldiniz!</h5>
      </div>
      <div class="card-body">Yarışmaya Başlamak için yarışmaya başla buttonuna basın</div>
      <div class="card-footer">
        <button class="btn btn-primary" @click="basla">Yarışmaya Başla</button>
      </div> 
    </div>
    <div class="card" v-else>
      <div class="card-header"><h3 class="mb-0">{{mevcutSoru.soru}}</h3></div>
      <div class="card-body">
        <div class="d-flex">
          <div class="harf shadow mr-3" v-for="(harf,index) in harfler" :key="'harf-'+index">
            <span v-if="harf.acildi">{{harf.harf}}</span>
            <span v-else></span>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <div class="d-flex">
          <div class="mr-4">Harf puan {{harfPuan}}</div>
          <div class="mr-4">Toplam puan {{puan}}</div>
          <div class="mr-4">Kalan süreniz <kbd>{{kalanSure}}</kbd></div>
        </div>
      </div>
      <div class="card-footer" :class="mesajClass" v-if="mesaj">{{mesaj}}</div>
      <div class="card-footer">
        <div class="input-group mb-3">
           <input
            class="form-control"
            type="text"
            placeholder="Cevap giriniz"
            v-model="yarismaciCevap"
          />
          <div class="input-group-append">
                  <button class="btn btn-success" @click="cevapVer">Cevap Ver</button>
          </div>
        </div>
 
      </div>
      <div class="card-footer">
        <button class="btn btn-secondary" @click="harfVer">Harf ver</button>
      </div>
    </div>
  </div>
</template>

<script>
import { setInterval, clearInterval, setTimeout } from 'timers';



export default {
  name: "app",

  components: {},
  data() {
    return {
      sorular: [
        {
          soru: "Siyah ile aynı anlama gelen bir renk",
          cevap: "Kara",
          soruldu: false
        },
        {
          soru: "Sık kullanılan bir isim",
          cevap: "Ahmet",
          soruldu: false
        },
        {
          soru: "Türkiye'nin başkenti",
          cevap: "Ankara",
          soruldu: false
        },
        {
          soru: "Karadenizde bir ilimiz",
          cevap: "Giresun",
          soruldu: false
        }
      ],
      mesaj:null,
      mesajClass:"",
      mesajSure:null,
      mevcutSoru: null,
      harfler: [],
      puan: 0,
      harfPuan: 0,
      yarismaciCevap: "",
      tamamlandi:false,
      sure :null,
      kalanSure: 0
    };
  },
  methods: {
    mesajGoster(mesaj, tur){
      this.mesaj = mesaj;
      if (tur==="hata") {
        this.mesajClass ="bg-danger text-white";
      } else if (tur ==="basarili") {
        this.mesajClass ="bg-success text-white";
      } else {
        this.mesajClass ="bg-dark text-white";
      }
      if( this.mesajSure) {
        clearTimeout(this.mesajSure);
        this.mesajSure=null;
      }
      this.mesajSure = setTimeout(()=>this.mesaj=null,3000);
    },
    basla() {
      this.tamamlandi =false;
      this.mevcutSoru =null;
      this.puan =0;
      this.sorular.map(x=>{
      x.soruldu =false});
      this.kalanSure =60;
      this.sure = setInterval(() => {
          this.kalanSure--;
          if (this.kalanSure === 0) {
            this.bitir();
          }
      } ,1000);

      this.soruVer();
    },
    bitir() {
      this.tamamlandi=true;
      mevcutSoru=null;
      clearInterval(this.sure);
    },
    soruVer() {
      this.yarismaciCevap ='';
      this.mevcutSoru = this.sorular.find(x => !x.soruldu);

      if (!this.mevcutSoru) {
        this.bitir();
        return;
      }

      this.harfler = [];
      this.mevcutSoru.cevap.split("").map(x => {
        this.harfler.push({
          harf: x,
          acildi: false
        });
      });
      this.harfPuan = this.harfler.length * 100;
      this.mevcutSoru.soruldu = true;
    },
    harfVer() {
      let rastgeleHarfIndex = Math.floor(this.harfler.length * Math.random());

      if (this.harfPuan <= 100) {
        return;
      }

      let harf = this.harfler[rastgeleHarfIndex];
      while (harf.acildi) {
        rastgeleHarfIndex = Math.floor(this.harfler.length * Math.random());
        harf = this.harfler[rastgeleHarfIndex];
      }
      harf.acildi = true;
      this.harfPuan -= 100;
    },
    cevapVer() {
      let cevap = this.yarismaciCevap.toLocaleUpperCase("tr");
      this.yarismaciCevap = cevap;
      if (
        this.mevcutSoru.cevap.toLocaleUpperCase("tr") ===
        cevap.toLocaleUpperCase("tr")
      ) {
        this.puan += this.harfPuan;
      } 
      else {
       this.puan -= this.harfPuan;
      }

      this.soruVer();
    }
  }
};
</script>

<style>
.harf {
  width: 100px;
  height: 100px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 30pt;
}
</style>
